// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/ststest/v1alpha1.StsTester":       schema_pkg_apis_ststest_v1alpha1_StsTester(ref),
		"./pkg/apis/ststest/v1alpha1.StsTesterSpec":   schema_pkg_apis_ststest_v1alpha1_StsTesterSpec(ref),
		"./pkg/apis/ststest/v1alpha1.StsTesterStatus": schema_pkg_apis_ststest_v1alpha1_StsTesterStatus(ref),
	}
}

func schema_pkg_apis_ststest_v1alpha1_StsTester(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StsTester is the Schema for the ststesters API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/ststest/v1alpha1.StsTesterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/ststest/v1alpha1.StsTesterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/ststest/v1alpha1.StsTesterSpec", "./pkg/apis/ststest/v1alpha1.StsTesterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_ststest_v1alpha1_StsTesterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StsTesterSpec defines the desired state of StsTester",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_ststest_v1alpha1_StsTesterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StsTesterStatus defines the observed state of StsTester",
				Type:        []string{"object"},
			},
		},
	}
}
